Update multitech.sc
scriptpacks/survival pull request #6
Opened 2022-04-19 19:18 UTC by Pi3tro88

2022-04-19 20:59 UTC, BisUmTo requested changes

2022-04-19 20:59 UTC, BisUmTo commented on multitech.sc
> +    _(c)->'/reIntroduceFallingBlockEntityPhase true',
Unknown command

2022-04-20 07:46 UTC, BisUmTo commented on multitech.sc
> +    _(c)->'/carpet-fixes reIntroduceFallingBlockEntityPhase true',
È voluto che la regola si disabili al riavvio?

2022-04-20 07:47 UTC, Pi3tro88 commented on multitech.sc
> +    _(c)->'/carpet-fixes reIntroduceFallingBlockEntityPhase true',
ahhhhhh ahahahha

2022-04-20 07:48 UTC, BisUmTo approved these changes

2022-04-20 07:48 UTC, merged

2022-04-21 05:32 UTC, BisUmTo commented on multitech.sc
> +    _(c)->'/carpet setDefault pcaSyncPlayerEntity true'
everyone