added ctrlqcrafingfix.sc
scriptpacks/survival pull request #7
Opened 2022-04-20 10:46 UTC by Pi3tro88

2022-04-21 05:27 UTC, BisUmTo requested changes

2022-04-21 05:27 UTC, BisUmTo commented on multitech.sc
> +    _(c)->'/carpet setDefault ctrlQCraftingFix true
Manca la virgoletta a fine riga...
Prova lo script prima di fare commit

2022-04-21 10:15 UTC, Pi3tro88 commented on multitech.sc
> +    _(c)->'/carpet setDefault ctrlQCraftingFix true
sorry ahah sbaglio sempre qualcosa

2022-04-23 17:00 UTC, BisUmTo approved these changes

2022-04-23 17:01 UTC, merged